name: Weibo Data Scraper

on:
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub's Actions tab

jobs:
  scrape-weibo:
    runs-on: ubuntu-latest  # Specify the environment for this job

    steps:
      # Step 1: Check out the repository code
      - name: Check out the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your desired Python version, like 3.9 or 3.10

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installs all dependencies listed in your requirements file

      # Step 4: Run the Weibo scraper
      - name: Run Weibo Scraper
        run: |
          python your_script.py  # Replace `your_script.py` with the actual name of your Python script
